### PR TITLE
Added color and background support for PDF

### PR DESCRIPTION
**Pull request by Vluf**

### CODE REVIEW

**Comment by Vluf** [comment]
If possible, can you release a new version so that I can use this update from PyPi?

**Comment by heuer** [comment]
Thanks for your contribution, Serge.

I think it would be nice if the color and background parameters would occur after the "border" parameter. Although it may break backward compatibility (IMO most users use the keyword arguments, so ordering doesn't matter and they wouldn't recognise a backward compatbility break). The function should use the same parameter ordering like write_svg, write_png etc.

Further, both color parameters should use the same syntax, i.e. a hexadecimal value. Currently it is mixed (hex vs. color name "white").

I'll prepare a release after the Easter holidays. 

Either you'll update the PR or I'll do the necessary changes.

**Comment by Vluf** [comment]
Updated the PR with the necessary changes.

**Comment by heuer** [comment]
Thanks for the update, I'll apply the patch within the next days.

**Comment by heuer** [comment]
Hi Serge,
Thanks again for your code. I modified a bit and made a release. You can download Segno 0.2.9 via PyPi.
Thanks and best regards
Lars

**Pull request closed without merging**
