### PR TITLE
Add an option to print QR codes in the terminal with half-block characters.

### PR DESCRIPTION
**Pull request by christian-oudard**
Added an option `qr.terminal(compact=True)`, which uses unicode half-block characters to print to the terminal in half the space.

### CODE REVIEW

**Comment by christian-oudard** [comment]
How necessary is it to use proper color coding in this PR?

**Comment by heuer** [comment]
Thanks for your submission. I'll take a lot at it this weekend.
Regarding colors: The default terminal output does not use any color at all. I guess colors may be ignored.

**Comment by christian-oudard** [comment]
I added a unittest today. The test has a triple-quoted QR code written directly in Python, which may not be your preferred style, please adjust as necessary.

**Comment by heuer** [comment]
@christian-oudard, I modified your code a bit. What do you think? 
I'll do some tests in different environments (Win, Linux, Mac) and merge the branch into master.

**Comment by christian-oudard** [comment]
Your updates look good. So happy it's easy to get this merged.

**Comment by christian-oudard** [comment]
Any way we could get this merged to master? We're still using the half-block feature from a fork in MobileCoin CLI.

**Comment by heuer** [comment]
> Since this pull request was mentioned again, can I once again request that it get merged?

Sorry for the looong delay.

Although I like the idea and appreciate your contribution, the change have more impacts for Segno than initially thought and I haven't found the time for thinking about it.

The change effects among other things QRCodeSequence, Python typing and the CLI  and requires more test cases than one.

I work on this issue / PR and you can expect a new release with your contribution soon.

**Comment by heuer** [comment]
Released 1.4.0 today with your contribution. Thanks again! :+1:

**Pull request closed without merging**
